export const apiData = {
  endpoints: [
    {
      name: "Get Borrower Pipeline",
      method: "GET",
      url: "/api/borrowers/pipeline",
      response: {
        new: [
          { id: "1", name: "Sarah Dunn", loan_type: "Home Loan", amount: 300000, status: "Renew" },
          { id: "3", name: "Lisa Carter", loan_type: "Home Loan", amount: 450000, status: "New" },
        ],
        in_review: [
          { id: "2", name: "Alan Matthews", loan_type: "Personal Loan", amount: 20000, status: "In Review" },
        ],
        approved: [],
      },
    },
    {
      name: "Get Borrower Detail",
      method: "GET",
      url: "/api/borrowers/{id}",
      response: [
        {
          id: "1",
          name: "Sarah Dunn",
          email: "sarah.dunn@example.com",
          phone: "(355)123-4557",
          loan_amount: 300000,
          status: "In Review",
          employment: "At Tech Company",
          income: 120000,
          existing_loan: 240000,
          credit_score: 720,
          source_of_funds: "Declared",
          risk_signal: "Missing Source of Funds declaration",
          ai_flags: [
            "Income Inconsistent with Bank statements",
            "High Debt-to-Income Ratio detected",
          ],
        },
        {
          id: "2",
          name: "Alan Matthews",
          email: "alan.matthews@example.com",
          phone: "(555)987-6543",
          loan_amount: 20000,
          status: "In Review",
          employment: "Freelancer",
          income: 80000,
          existing_loan: 10000,
          credit_score: 680,
          source_of_funds: "Declared",
          risk_signal: "Low Credit Score",
          ai_flags: ["Recent Credit Inquiries"],
        },
        {
          id: "3",
          name: "Lisa Carter",
          email: "lisa.carter@example.com",
          phone: "(555)456-7890",
          loan_amount: 450000,
          status: "New",
          employment: "Marketing Manager",
          income: 150000,
          existing_loan: 300000,
          credit_score: 740,
          source_of_funds: "Declared",
          risk_signal: "",
          ai_flags: [],
        },
      ],
    },
    {
      name: "Request Documents",
      method: "POST",
      url: "/api/borrowers/{id}/request-documents",
      response: {
        success: true,
        message: "Documents requested.",
      },
    },
    {
      name: "Send to Valuer",
      method: "POST",
      url: "/api/borrowers/{id}/send-valuer",
      response: {
        success: true,
        message: "Valuer notified.",
      },
    },
    {
      name: "Approve Loan",
      method: "POST",
      url: "/api/borrowers/{id}/approve",
      response: {
        success: true,
        message: "Loan approved.",
      },
    },
    {
      name: "Escalate to Credit Committee",
      method: "POST",
      url: "/api/borrowers/{id}/escalate",
      response: {
        success: true,
        message: "Escalated to Credit Committee.",
      },
    },
    {
      name: "Get Broker Info",
      method: "GET",
      url: "/api/broker/{id}",
      response: {
        name: "Robert Turner",
        deals: 16,
        approval_rate: "75%",
        pending: 7660,
      },
    },
    {
      name: "Get Onboarding Workflow",
      method: "GET",
      url: "/api/onboarding/workflow",
      response: {
        steps: [
          "Deal Intake",
          "IDV & Credit Check",
          "Document Upload",
          "AI Validation",
          "Credit Committee",
          "Approval & Docs",
          "Funder Syndication",
        ],
      },
    },
  ],
};